# [START gae_python37_cloudsql_config]
runtime: python37

instance_class : F4_1G

env_variables:
  CLOUD_SQL_USERNAME: db-user
  CLOUD_SQL_PASSWORD: GotongRoyong
  CLOUD_SQL_DATABASE_NAME: MedicareDB
  CLOUD_SQL_CONNECTION_NAME: 'hale-facet-314105:asia-southeast2:medicare-db'
# [END gae_python37_cloudsql_config]

